name = input("Enter Name:" )
age = int(input("Enter Age:" ))
city = input("Enter City:" )
mobile = input("Enter Mobile Number:" )

print("\n----- profile -----")
print("Name:",name)
print("Age:",age)
print("City:",city)
print("Mobile:",mobile)
